### ISSUE TITLE
AttributeError: 'IconizeEvent' object has no attribute 'Iconized'

### ISSUE THREAD

**Issue by QGB** [pointhi/kicad-python#6]
```
Traceback (most recent call last):
  File "C:\Program Files\KiCad\6.0\share\kicad\scripting\kicad_pyshell\kicad_pyeditor.py", line 121, in OnIconize
    self.iconized = event.Iconized()
AttributeError: 'IconizeEvent' object has no attribute 'Iconized'

```

**Comment by QGB** [comment]
```

Message: '\x1b[33mPress CTRL+C to quit\x1b[0m'
Arguments: ()


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\werkzeug\_internal.py", line 224, in _log
    getattr(_logger, type)(message.rstrip(), *args, **kwargs)


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\werkzeug\serving.py", line 1085, in run_simple
    _log("info", _ansi_style("Press CTRL+C to quit", "yellow"))

  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\flask\app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 980, in _bootstrap_inner
    self.run()


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 937, in _bootstrap
    self._bootstrap_inner()

Call stack:


AttributeError: 'NoneType' object has no attribute 'write'


  File "C:\Program Files\KiCad\6.0\bin\Lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)


Traceback (most recent call last):

--- Logging error ---

Message: '\x1b[31m\x1b[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\x1b[0m\n * Running on all addresses (0.0.0.0)\n * Running on http://127.0.0.1:5096\n * Running on http://192.168.1.3:5096'
Arguments: ()


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\werkzeug\_internal.py", line 224, in _log
    getattr(_logger, type)(message.rstrip(), *args, **kwargs)


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\werkzeug\serving.py", line 787, in log_startup
    _log("info", "\n".join(messages))


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\werkzeug\serving.py", line 1084, in run_simple
    srv.log_startup()


  File "C:\Users\qgb\Documents\KiCad\6.0\3rdparty\Python39\site-packages\flask\app.py", line 1188, in run
    run_simple(t.cast(str, host), port, self, **options)


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 980, in _bootstrap_inner
    self.run()


  File "C:\Program Files\KiCad\6.0\bin\Lib\threading.py", line 937, in _bootstrap
    self._bootstrap_inner()

Call stack:


AttributeError: 'NoneType' object has no attribute 'write'


  File "C:\Program Files\KiCad\6.0\bin\Lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)


Traceback (most recent call last):

--- Logging error ---
```
